version: '3'
services:
    postgres:
        image: postgres:13.0
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - postgres13-data:/var/lib/postgresql/data
          - ./postgres-data:/postgres-data
        ports:
          - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:4.26
        ports:
          - "8080:80"
        environment:
          - PGADMIN_DEFAULT_EMAIL=user@user.com
          - PGADMIN_DEFAULT_PASSWORD=postgres
        volumes:
          - pgAdmin4.26-data:/var/lib/pgadmin
          - ./pgadmin-data:/var/lib/pgadmin/storage

    neo4j:
        image: neo4j:4.4.3-community
        ports:
          - "7474:7474" # Browser
          - "7687:7687"
        volumes:
          - neo4j4.4.3-data:/data
        environment:
          NEO4J_AUTH: "none"

    mongo:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      volumes:
        - ./mongo:/data/examples

volumes:
  pgAdmin4.26-data:
  postgres13-data:
  neo4j4.4.3-data:
